"""
PDF Report Generator for Optical Link Budget Calculator
Generates professional PDFs with watermark
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os

class WatermarkCanvas(canvas.Canvas):
    """Custom canvas class to add watermark to every page"""
    
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []
    
    def showPage(self):
        self.pages.append(dict(self.__dict__))
        self._startPage()
    
    def save(self):
        """Add watermark to all pages before saving"""
        num_pages = len(self.pages)
        for page_num, page in enumerate(self.pages, 1):
            self.__dict__.update(page)
            self.draw_watermark(page_num, num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)
    
    def draw_watermark(self, page_num, total_pages):
        """Draw watermark on each page"""
        self.saveState()
        
        # Diagonal watermark in center
        self.setFillColorRGB(0.9, 0.9, 0.9, alpha=0.3)
        self.setFont("Helvetica-Bold", 60)
        self.translate(letter[0]/2, letter[1]/2)
        self.rotate(45)
        self.drawCentredString(0, 0, "OPTICAL LINK CALCULATOR")
        
        self.restoreState()
        
        # Footer watermark
        self.saveState()
        self.setFillColorRGB(0.3, 0.3, 0.3)
        self.setFont("Helvetica", 8)
        self.drawString(0.5*inch, 0.5*inch, 
                       f"Generated by Optical Link Budget Calculator | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        self.drawRightString(letter[0] - 0.5*inch, 0.5*inch, 
                            f"Page {page_num} of {total_pages}")
        self.restoreState()

def generate_pdf_report(calculation_data: dict, output_path: str):
    """
    Generate a professional PDF report with calculation results
    
    Args:
        calculation_data: Dictionary containing inputs and outputs
        output_path: Path where PDF should be saved
    """
    # Create document with custom canvas (for watermark)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=1*inch,
        bottomMargin=1*inch
    )
    
    # Container for document elements
    story = []
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#007bff'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#007bff'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    subheading_style = ParagraphStyle(
        'CustomSubHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#0056b3'),
        spaceAfter=10,
        spaceBefore=10
    )
    
    normal_style = styles['Normal']
    
    # ===== TITLE PAGE =====
    title = Paragraph("Optical Link Budget Calculation Report", title_style)
    story.append(title)
    story.append(Spacer(1, 0.3*inch))
    
    # Timestamp
    timestamp = Paragraph(
        f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %H:%M:%S')}",
        normal_style
    )
    story.append(timestamp)
    story.append(Spacer(1, 0.5*inch))
    
    # ===== INPUT PARAMETERS =====
    story.append(Paragraph("Input Parameters", heading_style))
    story.append(Spacer(1, 0.1*inch))
    
    inputs = calculation_data.get('inputs', {})
    outputs = calculation_data.get('outputs', {})
    
    input_data = [
        ['Parameter', 'Value', 'Unit'],
        ['Transmitter Power', f"{inputs.get('tx_power', 0):.2f} dBm ({outputs.get('tx_power_mw', 0):.6f} mW)", ''],
        ['Transmitter Efficiency', f"{inputs.get('tx_efficiency', 0):.2f}", '%'],
        ['Receiver Efficiency', f"{inputs.get('rx_efficiency', 0):.2f}", '%'],
        ['Receiver Sensitivity', f"{inputs.get('rx_sensitivity', 0):.2f} dBm ({outputs.get('rx_sensitivity_mw', 0):.9f} mW)", ''],
        ['Optical Wavelength', f"{inputs.get('wavelength', 0):.2f}", 'nm'],
        ['Transmitter Diameter', f"{inputs.get('tx_diameter', 0):.3f}", 'm'],
        ['Receiver Diameter', f"{inputs.get('rx_diameter', 0):.3f}", 'm'],
        ['Distance', f"{inputs.get('distance', 0):.2f} m ({inputs.get('distance', 0)/1000:.3f} km)", ''],
        ['Implementation Loss', f"{inputs.get('impl_loss', 0):.2f}", 'dB'],
        ['Coupling Loss', f"{inputs.get('coupling_loss', 0):.2f}", 'dB'],
        ['Tx Pointing Loss', f"{inputs.get('tx_pointing_loss', 0):.2f}", 'dB'],
        ['Rx Pointing Loss', f"{inputs.get('rx_pointing_loss', 0):.2f}", 'dB'],
    ]
    
    input_table = Table(input_data, colWidths=[2.5*inch, 3.5*inch, 0.5*inch])
    input_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#007bff')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    
    story.append(input_table)
    story.append(Spacer(1, 0.5*inch))
    
    # ===== CALCULATION RESULTS =====
    story.append(Paragraph("Calculation Results", heading_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Antenna Gains
    story.append(Paragraph("Antenna Gains", subheading_style))
    
    gain_data = [
        ['Parameter', 'Absolute', 'dB'],
        ['Transmitter Gain', f"{outputs.get('tx_gain_absolute', 0):.4e}", f"{outputs.get('tx_gain_db', 0):.2f}"],
        ['Receiver Gain', f"{outputs.get('rx_gain_absolute', 0):.4e}", f"{outputs.get('rx_gain_db', 0):.2f}"],
    ]
    
    gain_table = Table(gain_data, colWidths=[3*inch, 2*inch, 1.5*inch])
    gain_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0056b3')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    
    story.append(gain_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Beam Divergence
    story.append(Paragraph("Beam Divergence", subheading_style))
    
    divergence_data = [
        ['Parameter', 'Radians', 'Degrees'],
        ['Tx Beam Divergence', f"{outputs.get('tx_beam_divergence_rad', 0):.6e}", 
         f"{outputs.get('tx_beam_divergence_deg', 0):.6f}"],
        ['Rx Beam Divergence', f"{outputs.get('rx_beam_divergence_rad', 0):.6e}", 
         f"{outputs.get('rx_beam_divergence_deg', 0):.6f}"],
    ]
    
    divergence_table = Table(divergence_data, colWidths=[3*inch, 2*inch, 1.5*inch])
    divergence_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0056b3')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    
    story.append(divergence_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Losses
    story.append(Paragraph("Losses", subheading_style))
    
    loss_data = [
        ['Loss Type', 'Value (dB)'],
        ['Free Space Path Loss', f"{outputs.get('path_loss_db', 0):.2f}"],
        ['Implementation Loss', f"{outputs.get('impl_loss_db', 0):.2f}"],
        ['Coupling Loss', f"{outputs.get('coupling_loss_db', 0):.2f}"],
        ['Tx Pointing Loss', f"{outputs.get('tx_pointing_loss_db', 0):.2f}"],
        ['Rx Pointing Loss', f"{outputs.get('rx_pointing_loss_db', 0):.2f}"],
        ['Total Losses', f"{outputs.get('total_loss_db', 0):.2f}"],
    ]
    
    loss_table = Table(loss_data, colWidths=[4*inch, 2.5*inch])
    loss_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0056b3')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f8f9fa')]),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#ffc107')),
    ]))
    
    story.append(loss_table)
    story.append(Spacer(1, 0.5*inch))
    
    # ===== FINAL RESULTS - LINK MARGIN HIGHLIGHT =====
    story.append(PageBreak())
    story.append(Paragraph("Power Budget Summary", heading_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Link Margin - Large prominent display
    link_margin = outputs.get('link_margin_db', 0)
    # Calculate margin in mW (difference between received and required)
    link_margin_mw = outputs.get('received_power_mw', 0) - outputs.get('rx_sensitivity_mw', 0)
    
    if link_margin > 0:
        status = "✓ LINK VIABLE"
        status_color = colors.HexColor('#28a745')
        margin_bg = colors.HexColor('#d4edda')
    else:
        status = "✗ LINK NOT VIABLE"
        status_color = colors.HexColor('#dc3545')
        margin_bg = colors.HexColor('#f8d7da')
    
    margin_display = [
        ['LINK MARGIN', f"{link_margin:.2f} dB ({link_margin_mw:.6f} mW)"],
        ['STATUS', status],
    ]
    
    margin_table = Table(margin_display, colWidths=[3*inch, 3.5*inch])
    margin_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), margin_bg),
        ('TEXTCOLOR', (0, 0), (-1, -1), status_color),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 24),
        ('GRID', (0, 0), (-1, -1), 3, status_color),
        ('TOPPADDING', (0, 0), (-1, -1), 20),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
    ]))
    
    story.append(margin_table)
    story.append(Spacer(1, 0.5*inch))
    
    # Power Details
    story.append(Paragraph("Power Details", subheading_style))
    
    power_data = [
        ['Parameter', 'dBm', 'mW (Watts)'],
        ['Received Power', 
         f"{outputs.get('received_power_dbm', 0):.2f}", 
         f"{outputs.get('received_power_mw', 0):.6f} ({outputs.get('received_power_w', 0):.9f})"],
        ['Receiver Sensitivity (Required)', 
         f"{outputs.get('rx_sensitivity_dbm', 0):.2f}", 
         f"{outputs.get('rx_sensitivity_mw', 0):.9f} ({outputs.get('rx_sensitivity_mw', 0)/1000:.12f})"],
        ['Transmitter Power', 
         f"{outputs.get('tx_power_dbm', 0):.2f}", 
         f"{outputs.get('tx_power_mw', 0):.6f} ({outputs.get('tx_power_mw', 0)/1000:.9f})"],
    ]
    
    power_table = Table(power_data, colWidths=[2.5*inch, 1.5*inch, 2.5*inch])
    power_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#007bff')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    
    story.append(power_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Efficiency Summary
    story.append(Paragraph("Efficiency Summary", subheading_style))
    
    efficiency_data = [
        ['Component', 'Efficiency (%)'],
        ['Transmitter', f"{outputs.get('tx_efficiency_percent', 0):.2f}%"],
        ['Receiver', f"{outputs.get('rx_efficiency_percent', 0):.2f}%"],
    ]
    
    efficiency_table = Table(efficiency_data, colWidths=[3*inch, 3.5*inch])
    efficiency_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0056b3')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    
    story.append(efficiency_table)
    story.append(Spacer(1, 0.5*inch))
    
    # Notes section
    story.append(Paragraph("Notes", subheading_style))
    notes_text = """
    • Link Margin indicates how much power headroom exists above the minimum required
    • Positive link margin means the link is viable
    • A link margin of 3-6 dB is typically recommended for reliable operation
    • This calculation assumes ideal atmospheric conditions
    • Actual performance may vary based on environmental factors
    """
    story.append(Paragraph(notes_text, normal_style))
    
    # Build PDF with watermark
    doc.build(story, canvasmaker=WatermarkCanvas)
    
    return output_path

# FastAPI endpoint integration
from fastapi import FastAPI
from fastapi.responses import FileResponse
import tempfile

def create_pdf_endpoint(app: FastAPI):
    """Add PDF generation endpoint to FastAPI app"""
    
    @app.post("/api/generate-pdf")
    async def generate_pdf(calculation_data: dict):
        """
        Generate PDF report for calculation
        
        Args:
            calculation_data: Complete calculation data
        
        Returns:
            PDF file download
        """
        try:
            # Create temporary file
            with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp:
                output_path = tmp.name
            
            # Generate PDF
            generate_pdf_report(calculation_data, output_path)
            
            # Return file for download
            return FileResponse(
                output_path,
                media_type='application/pdf',
                filename=f"optical_link_calculation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            )
            
        except Exception as e:
            from fastapi import HTTPException
            raise HTTPException(status_code=500, detail=f"PDF generation error: {str(e)}")
